kind: pipeline
name: default

steps:
- name: test
  image: maven:3.6-jdk-8
  commands:
  - mvn install -DskipTests=true -Dmaven.javadoc.skip=true -B -V
  - mvn test -B
- name: docker  
  image: plugins/docker
  settings:
    username: hygl
    password: cloudnative
    repo: hygl/java-spring-boot2