resources:
- name: source-code
  type:  git
  check_every: 5m
  source: 
    uri: https://github.com/hygl/spring-boot-example.git
    branch: master
jobs:
- name: build
  plan:
    - get: source-code
      trigger: true
    - task: test
      config:
        platform: linux
        image_resource:
          type: docker-image
          source: 
            repository: maven
            tag: 3.6-jdk-11
        inputs: 
          - name: source-code
        outputs:
          - name: build
        caches:
          - path: source-code/.m2
        run:
          path: sh
          args:
          - -c
          - mvn -f source-code/pom.xml test -Dmaven.repo.local=source-code/.m2
            # cp code/spring-boot/target/*.jar build/runner.jar 
    - task: build-image
      config:
        platform: linux
        image_resource:
          type: docker-image
          source: 
            repository: maven
            tag: 3.6-jdk-11
        inputs: 
          - name: code
        outputs:
          - name: build
        caches:
          - path: source-code/.m2
        run:
          path: sh
          args:
          - -c
          - mvn -f source-code/pom.xml spring-boot:build-image -Dmaven.repo.local=source-code/.m2
            # cp code/spring-boot/target/*.jar build/runner.jar 
    